backend:
  name: github
  branch: master
  repo: cedricdollars/eshop

media_folder: static/assets
public_folder: /assets

collections: 
  - name: product
    label: Produit
    folder: products
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    create: true
    fields: 
      - { name: title, required: true, label: Titre}
      - { name: price, required: false, label: Prix, default: "5"}
      - { name: quantity, required: false, label: Quantity, default: "100"}
      - { name: description, required: false, label: Description, widget: markdown, default: "None"}
      - { name: image, required: true, label: Image, widget: image}
      - { name: path, required: true, label: Path}
      

  - name: lit
    label: lit
    folder: /src/products/lits
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    create: true
    fields: 
      - { name: title, required: true, label: Titre}
      - { name: price, required: false, label: Prix, default: "5"}
      - { name: quantity, required: false, label: Quantity, default: "100"}
      - { name: description, required: false, label: Description, widget: markdown, default: "None"}
      - { name: image, required: true, label: Image, widget: image}
      - { name: path, required: true, label: Path}
      
  - name: carousel
    label: carousel
    folder: /src/components/carousel
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    create: true
    fields:
      - { name: image, required: true, label: Image, widget: image}
      - { name: path, required: true, label: Path}
      - { name: title, required: true, label: Titre}
      - { name: price, required: false, label: Prix, default: "5"}
  
  - name: blog
    label: blog
    folder: /src/blogs
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    create: true
    fields:
      - { name: title, required: true, label: Titre}
      - { name: image, required: true, label: Image, widget: image}
      - { name: path, required: true, label: Path}
      - { name: description, required: true, label: description}
 